# Generated by Django 6.0.4 on 2026-06-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('beach', 'Beach'), ('nature', 'Nature'), ('hill', 'Hill Station'), ('city', 'City Tour'), ('religious', 'Religious'), ('culture', 'Culture'), ('spiritual', 'Spiritual')], default='adventure', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(),
        ),
    ]
