# Generated by Django 6.0.4 on 2026-06-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_category_alter_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('spiritual', 'Spiritual'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('heritage', 'Heritage'), ('relaxation', 'Relaxation'), ('wildlife', 'Wildlife'), ('beach', 'Beach')], default='adventure', max_length=50),
        ),
    ]
